### PR TITLE
rich Text Editor

### PR DESCRIPTION
**Pull request by ArjunGTX**
- Integrated `react-quill` library 
- Minor UI fixes

### CODE REVIEW

**Review by AmishMishra11 — COMMENTED** [review]
Sign up is not working so you might want to fix that
Other that that everything is good

**Comment by ArjunGTX** [comment]
> Sign up is not working so you might want to fix that Other that that everything is good

Thankyou for pointing out. It has been fixed

**Review by AmishMishra11 — APPROVED** [review]
Yep working fine now

**Review by ajay-mandaviya — APPROVED** [review]
everything looks good and well structure to me , no need any suggestion from me

**Pull request merged**
